name: The Secret Of Everything
favicon: null
layout_spectrum: 0.41695431247353554
typography_spectrum: 0.7384729508776218
title: The Secret of Everything
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.6270332643762231
  lightness: 0.5435795478988439
  saturation: 0.9037098088301718
  rhythmicContrast: 0.8926830261480063
purpose: []
